### ISSUE TITLE
curl: (3) URL using bad/illegal format or missing URL

### ISSUE THREAD

**Issue by dasauto1** [samsepiol59/best-discord-notifications#1]
Trying to run the [user] script for Sonarr on debian 10, installed jq and running in to this error:

`curl: (3) URL using bad/illegal format or missing URL`

Happy to provide more information as required.

Thanks.

**Comment by samsepiol59** [comment]
I'll be straight with you, I'm no expert on code or anything hehe

But, I think you might have set something wrong - maybe the api keys? If you can, copy-paste the whole config file (with your keys/webhooks in it) in an unlisted pastebin.com file with bash syntax highlighting! Then share the link here, and I can take a look!

**Comment by dasauto1** [comment]
I did triple check. I also changed the `jpg` links probably that might be an issue, will try and run the script with only the api changes and nothing else and report back. If doesnt work will go the pastebin route. Thanks for taking the time.

**Comment by samsepiol59** [comment]
Great, let me know how it goes!

**Comment by dasauto1** [comment]
Unfortunately it still gives me the same error, I am sure it is curl syntax (which I am unable to rectify). here is the pastebin with the data

https://0bin.net/paste/dmttzT0qgcviy49I#

**Comment by dasauto1** [comment]
I realise that the correct arguments were not being passed. I see 

`$sonarr_episodefile_episodetitles,$sonarr_episodefile_seasonnumber,$sonarr_isupgrade,$sonarr_series_imdbid,$sonarr_series_title`

Are there any other I need to pass?

Thanks.

**Comment by samsepiol59** [comment]
Oh you're trying a dry run? Then there's some arguments you need to manually pass yeah, like episode number for TV shows, etc!

Those should be enough, I can send the fill list when I get back home!

**Comment by dasauto1** [comment]
No worries, may I suggest adding it to readme as well for others to identify the right parameters, I missed the `sonarr_series_title` argument.

Will test it in a few hours when sonarr grabs something. Thanks for your time.

**Comment by dasauto1** [comment]
Update: passing dummy arguments did not work and I get the same error. Of what I have read online it is due to cUrl syntax. 
Is there anyway I can get the one you are using that works so I can just change the api key and try it out?
Cheers

**Comment by dasauto1** [comment]
Thanks to JoseP noticed that the webhook variable is set as: `webhook_eb` but called as `webhook`, just changed that in the script to make it work.
